import { Metadata } from "next";
import Leftbar from "../components/layouts/Leftbar";


export const metadata: Metadata = {
  title: "Student's Portal",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex justify-between w-full">
      <div className="max-h-screen overflow-scroll bg-[#edeeee] h-screen">
        <Leftbar /> 
      </div>
      <div className="w-[85%] bg-[#ffffff]">
        {children}
      </div>
    </div>
  );
}
