import type { Metadata } from "next";
import "../globals.css";
import { Nunito_Sans } from 'next/font/google'
import LeftBar2 from "../components/layouts/LeftBar2";

const nunitoS = Nunito_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Class Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex justify-between w-full">
      <div className="max-h-screen overflow-scroll bg-[#edeeee] h-screen">
        <LeftBar2 /> 
      </div>
      <div className="w-[85%] bg-[#ffffff]">
        {children}
      </div>
    </div>
  );
}
