import type { Metadata } from "next";
import "./globals.css";
import { Nunito_Sans } from 'next/font/google'

const nunitoS = Nunito_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoS.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
